"""add tempo_medicao to sonus_uploads

Revision ID: 63fac055ad44
Revises: bba37caa8120
Create Date: 2026-03-19 15:06:31.823708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fac055ad44'
down_revision: Union[str, Sequence[str], None] = 'bba37caa8120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.alter_column('employees', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.alter_column('field_sheets', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('field_sheets', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('field_sheets', 'dosimeter_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('field_sheets', 'collection_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('field_sheets', 'technician_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('field_sheets', 'signature_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('field_sheets', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_field_sheets_id'), 'field_sheets', ['id'], unique=False)
    op.create_unique_constraint(None, 'field_sheets', ['laudo_number'])
    op.alter_column('generated_reports', 'field_sheet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('generated_reports', 'sonus_upload_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('generated_reports', 'output_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('generated_reports', 'output_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('generated_reports', 'sha256_output',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('generated_reports', 'generated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    op.add_column('sonus_uploads', sa.Column('tempo_medicao', sa.String(length=20), nullable=True))
    op.alter_column('sonus_uploads', 'field_sheet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sonus_uploads', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sonus_uploads', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('sonus_uploads', 'sha256_original',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('sonus_uploads', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_sonus_uploads_id'), 'sonus_uploads', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_sonus_uploads_id'), table_name='sonus_uploads')
    op.alter_column('sonus_uploads', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sonus_uploads', 'sha256_original',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('sonus_uploads', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('sonus_uploads', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sonus_uploads', 'field_sheet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sonus_uploads', 'tempo_medicao')
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.alter_column('generated_reports', 'generated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('generated_reports', 'sha256_output',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('generated_reports', 'output_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('generated_reports', 'output_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('generated_reports', 'sonus_upload_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('generated_reports', 'field_sheet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'field_sheets', type_='unique')
    op.drop_index(op.f('ix_field_sheets_id'), table_name='field_sheets')
    op.alter_column('field_sheets', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('field_sheets', 'signature_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('field_sheets', 'technician_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('field_sheets', 'collection_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('field_sheets', 'dosimeter_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('field_sheets', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('field_sheets', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.alter_column('employees', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
