"""add sonus_uploads

Revision ID: 70dd6f7e1e7f
Revises: 66ddbc5dd2d4
Create Date: 2026-02-26 13:38:07.641556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dd6f7e1e7f'
down_revision: Union[str, Sequence[str], None] = '66ddbc5dd2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sonus_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_sheet_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('parsed_employee_name', sa.String(length=150), nullable=True),
    sa.Column('inicio', sa.String(length=20), nullable=True),
    sa.Column('fim', sa.String(length=20), nullable=True),
    sa.Column('dose_diaria', sa.String(length=20), nullable=True),
    sa.Column('ne_db', sa.String(length=20), nullable=True),
    sa.Column('nen_db', sa.String(length=20), nullable=True),
    sa.Column('sha256_original', sa.String(length=64), nullable=False),
    sa.Column('upload_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_sheet_id'], ['field_sheets.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sonus_uploads_id'), 'sonus_uploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sonus_uploads_id'), table_name='sonus_uploads')
    op.drop_table('sonus_uploads')
    # ### end Alembic commands ###
