"""add generated_reports

Revision ID: b3f3e2445a5f
Revises: dfb3550a955c
Create Date: 2026-02-26 14:01:32.620323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f3e2445a5f'
down_revision: Union[str, Sequence[str], None] = 'dfb3550a955c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_sheet_id', sa.Integer(), nullable=False),
    sa.Column('sonus_upload_id', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=False),
    sa.Column('output_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256_output', sa.String(length=64), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['field_sheet_id'], ['field_sheets.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sonus_upload_id'], ['sonus_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    # ### end Alembic commands ###
