"""add fields to field_sheet

Revision ID: dfb3550a955c
Revises: 70dd6f7e1e7f
Create Date: 2026-02-26 13:58:20.623899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb3550a955c'
down_revision: Union[str, Sequence[str], None] = '70dd6f7e1e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_sheets', sa.Column('turno', sa.String(length=50), nullable=True))
    op.add_column('field_sheets', sa.Column('codigo_esocial', sa.String(length=50), nullable=True))
    op.add_column('field_sheets', sa.Column('pre_verificacao_db', sa.String(length=20), nullable=True))
    op.add_column('field_sheets', sa.Column('pos_verificacao_db', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_sheets', 'pos_verificacao_db')
    op.drop_column('field_sheets', 'pre_verificacao_db')
    op.drop_column('field_sheets', 'codigo_esocial')
    op.drop_column('field_sheets', 'turno')
    # ### end Alembic commands ###
