"""add_cnpj_to_companies

Revision ID: fd93756deedb
Revises: 63fac055ad44
Create Date: 2026-03-23 15:26:21.463314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd93756deedb'
down_revision: Union[str, Sequence[str], None] = '63fac055ad44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('cnpj', sa.String(length=18), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'cnpj')
    # ### end Alembic commands ###
